version: '3.5'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - "8080:8080"
    environment:
      - SERVICES=
      - DEFAULT_REGION=us-east-1
      - AWS_XRAY_SDK_ENABLED=true
      - DEBUG=${DEBUG- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - hostnet
networks:
  hostnet:
    external: true
    name: lambdanet
