spring:
  datasource:
    url: jdbc:postgresql://${AQTS_DATABASE_ADDRESS}:${AQTS_DATABASE_PORT}/${AQTS_DATABASE_NAME}?currentSchema=${AQTS_SCHEMA_NAME}
    username: ${AQTS_SCHEMA_OWNER_USERNAME}
    password: ${AQTS_SCHEMA_OWNER_PASSWORD}

logging:
  level:
    org.postgresql: DEBUG
    com.zaxxer: OFF
