spring:
  datasource:
    url: jdbc:postgresql://${WQP_DATABASE_ADDRESS}:5435/${WQP_DATABASE_NAME}
    username: ${WQP_DB_READ_ONLY_USERNAME}
    password: ${WQP_DB_READ_ONLY_PASSWORD}

logging:
  level:
    org.postgresql: DEBUG
    com.zaxxer: OFF
